---
title: opitzconsulting blog
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  topics:
    title: Topics
    output: true
    permalink: "/categories/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: topics
  values:
    layout: category
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: info@opitz-consulting.com
description: 'Hier schreiben Mitarbeiter von OPITZ CONSULTING zu Technologien, Werkzeugen,
  Methoden und anderen interessanten Erkenntnissen und Erlebnissen aus ihrem Arbeitsalltag
  bei und für unsere Kunden.

'
baseurl: ''
url: http://opitzconsulting.github.io
twitter_username: OC_WIRE
github_username: opitzconsulting
youtube_username: OPITZCONSULTING
google_analytics_code: UA-86969716-1
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
paginate: 5
gems:
- jekyll-paginate
paginate_path: "/pages/:num/"
